### PR TITLE
Fixed arm laser light displaying incorrect state

### PR DESCRIPTION
**Pull request by Gold872**
Instead of having a switch that can display the incorrect laser state, it now uses toggle buttons and only displays the laser state of the gripper data received

image

### CODE REVIEW

**Comment by Levi-Lesches** [comment]
We've tried this before, but had the issue that the UI isn't responsive to what you press, which makes people think the _Dashboard_ is broken. Currently, the metrics sidebar shows what the rover is actually doing while the switch we have now shows what you're trying to do. Not saying that's the best answer but an unresponsive UI isn't great either

Also, +1 for including a pic in the PR, -1 for keeping your auto-formatter on! It's tempting I know, but it distracts from the actual changes of the PR

**Comment by Gold872** [comment]
One other option I thought of (which I did in my other dashboard) is display what the user selected but have a check or X icon next to it to indicate whether or not the data the rover has is the one you want

Also where did I screw up formatting?

**Comment by Gold872** [comment]
Modified it so there's now an indicator displaying whether or not the states match

image

image

**Review by Levi-Lesches — DISMISSED** [review]
Perfect, thanks

**Review by Levi-Lesches — DISMISSED** [review]

**Review by Levi-Lesches — APPROVED** [review]

**Pull request merged**
